pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo "Our First Pipeline"

jobs:
- job: Firstjob
  timeoutInMinutes: 10
  steps:
  - bash: echo "The First job"

- job: Secondjob
  steps:
  - bash: echo "Our Second Pipeline"